DROP TABLE IF EXISTS users;

CREATE TABLE prompts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    username TEXT NOT NULL,
    text TEXT NOT NULL,
    elo INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE humanText ( 
    -- Add some way to link a prompt to every text chunk to display it nicely on the homepage
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    username TEXT NOT NULL,
    text TEXT NOT NULL,
    elo INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE botText (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    username TEXT NOT NULL,
    text TEXT NOT NULL,
    elo INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    username TEXT NOT NULL,
    password TEXT NOT NULL,
    elo INTEGER NOT NULL DEFAULT 0
);